CATEGORIES_NAMES = [
    "diamant",
    "or",
    "argent",
    "bronze",
    "lu_aussi",
    "en_train de lire",
    "pas_apprecie",
    "envies",
    "pile_a_lire",
]
BOOK_FIELDNAMES = [
    "title",
    "book_url",
    "cover",
    "resume",
    "authors",
    "authors_url",
    "dates",
    "dates_country",
    "price",
    "themes",
    "themes_url",
    "editors",
    "editors_url",
    "collections",
    "collections_url",
    "readers_count",
    "count_note_1",
    "count_note_2",
    "count_note_3",
    "count_note_4",
    "count_note_5",
    "count_note_6",
    "count_note_7",
    "count_note_8",
    "count_note_9",
    "count_note_10",
] + CATEGORIES_NAMES
BOOK_TOP_1000_FIELDNAMES = ["position"] + BOOK_FIELDNAMES
BOOK_TOP_1000_PRESENTATION = [
    "input",
    "markdown",
    "input",
    "markdown",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
    "input",
]
BOOK_TOP_1000_TYPE = [
    "numeric",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "numeric",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
]
BOOK_TOP_1000_COLUMNS_DASHBOARD = [
    {
        "name": book_field,
        "id": book_field,
        "type": book_type,
        "presentation": book_presentation,
    }
    for book_field, book_type, book_presentation in zip(
        BOOK_TOP_1000_FIELDNAMES, BOOK_TOP_1000_TYPE, BOOK_TOP_1000_PRESENTATION
    )
    if book_field != "book_url"
]
